[package]
name = "smt-api"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
smt-core = { path = "../smt-core" }
smt-engine = { path = "../smt-engine" }
smt-sat = { path = "../smt-sat" }
