[package]
name = "smt-tests"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
smt-api = { path = "../smt-api" }
smt-core = { path = "../smt-core" }
smt-engine = { path = "../smt-engine", features = ["test-debug"] }
smt-sat = { path = "../smt-sat" }
